spring.application.name=inventory-demo

spring.datasource.url=jdbc:h2:mem:inventorydb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.sql.init.mode=never

spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.completion-mode=archive
spring.modulith.events.republish-outstanding-events-on-restart=true

logging.level.org.springframework.modulith=DEBUG
logging.level.org.springframework.modulith.events=DEBUG
logging.level.org.springframework.jdbc=DEBUG