-- Spring Modulith 事件发布表
CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    EVENT_TYPE VARCHAR(512) NOT NULL,
    LISTENER_ID VARCHAR(512) NOT NULL,
    PUBLICATION_DATE TIMESTAMP(6) NOT NULL,
    COMPLETION_DATE TIMESTAMP(6),
    SERIALIZED_EVENT TEXT NOT NULL
);

-- Spring Modulith 事件归档表（completion-mode=archive 时使用）
CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION_ARCHIVE (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    EVENT_TYPE VARCHAR(512) NOT NULL,
    LISTENER_ID VARCHAR(512) NOT NULL,
    PUBLICATION_DATE TIMESTAMP(6) NOT NULL,
    COMPLETION_DATE TIMESTAMP(6),
    SERIALIZED_EVENT TEXT NOT NULL,
    ARCHIVED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);